name: Feature Request
description: "Suggest an idea for this project."
labels: 'feature'
assignees: []
body:
  - type: markdown
    attributes:
      value: |-
        **Important Notes:**

        *   Please ensure your request adheres to our [Code of Conduct](https://github.com/JorgeRojo/token-baker/blob/main/docs/CODE_OF_CONDUCT.md).
        *   For general contribution guidelines, please refer to our [Contributing Guidelines](https://github.com/JorgeRojo/token-baker/blob/main/docs/CONTRIBUTING.md).
        *   When suggesting code changes, please consider our [Code Style Guidelines](https://github.com/JorgeRojo/token-baker/blob/main/docs/CODE_STYLE.md).
  - type: textarea
    id: problem-related
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      placeholder: "Describe the problem here..."
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Describe the solution here..."
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Describe alternatives here..."
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Any other relevant information..."
